name: github-actions-workflow
on: [ push ]

jobs:
  check-go-version:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        uses: docker://golang:1.20.4-alpine3.17

      - run: go version
