name: github-actions-workflow
on: [ push ]

jobs:
  check-go-version:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://golang:1.20.4-alpine3.17

      - name: check-version
        run: go version

      - name: list
        run: ls -laF ..

      - name: run-app
        run: go run ./main.go